version: "3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
      - new_container
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
  new_container:
    image: nginx
    ports:
      - "8080:80"
